# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HiEfficiency' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
        pod 'React', :path => '../node_modules/react-native', :subspecs => [
           'Core',
           'CxxBridge',
           'DevSupport',
           'RCTAnimation',
           'RCTActionSheet',
           'RCTBlob',
           'RCTGeolocation',
           'RCTImage',
           'RCTLinkingIOS',
           'RCTNetwork',
           'RCTSettings',
           'RCTText',
           'RCTVibration',
           'RCTWebSocket'
	]  	
        pod 'Firebase/Core'  
        pod 'Firebase/Firestore'
        pod 'Firebase/Auth'
        pod 'yoga', path: "./../node_modules/react-native/ReactCommon/yoga/yoga.podspec"
        pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
        pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
        pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
   target 'HiEfficiency-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'HiEfficiencyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HiEfficiency-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end